// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhcfgqzucomkasmaesrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloY2ZncXp1Y29ta2FzbWFlc3JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MjY2NjMsImV4cCI6MjA2MTEwMjY2M30.WWFlbYAIey6Gl_LAB7ZG658JGYyeEAa-lRzgvTDUO8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);